### ISSUE TITLE
CSVファイルの仕様変更

### ISSUE THREAD

**Issue by inosy22** [TeamLS/6chefs2#1]
暗号化した場合にCSVファイルが長すぎると読み込めないバグを修正する。

対策案は以下の2つ
・CSVファイル読み込み時のバッファーの容量を大きくする
・JSON形式に変更する

**Comment by KoheiAsami2** [comment]
これ終わったの？
終わったらcloseしておいて

**Comment by RyoyaIno** [comment]
残念ながらまだ終わっていない
