### ISSUE TITLE
type:ending仕様変更

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#10]
スタッフロールを再生し、その後mapID:intのマップへChangeMap

**Comment by RyoyaIno** [comment]
これもコールバックイベントを用意して、EndingSceneはスタック使ったほうが拡張性あっていいような

**Comment by KoheiAsami2** [comment]
そうだね
EventインスタンスでEndingSceneのコールバック待ちをして、
コールバックされたらイベント実行するようにしようか

**Comment by inosy22** [comment]
これは最後の方でいいや

**Comment by inosy22** [comment]
現状、プログラムにエンディング処理を書き込んでしまっているので、変更する場合ビルドが必要
エンディングの内容等をイベントスクリプトもしくは単純なjsonファイルなどで保持して、ビルドせずに変更できるようにする。

**Comment by inazou** [comment]
event/ending.json(名前は固定)
```json
{
        "1":[
        ],
        "2":[
        ],
}
```
のidがendingのidと一致するようにする
```json
{
     "type":"ending",
      "id":"1"
},
```
