### ISSUE TITLE
【スクリプト追加】”type”:"stopRepeat"(繰り返しを止める命令)

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#102]
"type":"repeat"
"times":-1
"action"…
を書いたときに
{
   "type":"stopRepeat"
}
で繰り返し処理を止めて
次のアクションに行けるように

**Comment by KoheiAsami2** [comment]
Repeatっていうは複数同時に走っている場合もあるので、
Repeat自体にidやらなんやらが必要です。

**Comment by KoheiAsami2** [comment]
だから今回は
"stopRepeat"というか
"stopEvent"（code指定でイベントを止める）のような汎用イベントを作る必要あり

**Comment by KoheiAsami2** [comment]
設計的にはかなりシンプル
```cpp
class GameEvent : public Ref
{
  int code { -1 }; ⇦ 単位イベントの実体を表す識別子
  virtual void stop(); ⇦ イベントごとに止め方が異なるのでインターフェース
  virtual GameEvent* clone(); ⇦ おまけ。これ今後必要。自身の実体のコピーをメモリ上に作成する
};
```
を追加
GameEventのインスタンスがEventインスタンス持っている時（子イベント）
どうすれば子イベントを止めるかなんだけど、
```cpp
GameEvent::stop(int code = -1)
```
みたいにcode渡して再帰的に処理しよう

**Comment by KoheiAsami2** [comment]
#103
