### ISSUE TITLE
[戦闘イベ] 回避動作

### ISSUE THREAD

**Issue by inosy22** [TeamLS/6chefs2#113]
#8

type:battleの最中に
「移動キー+ダッシュキー+決定キー」
を押すと、スタミナを消費して回避動作をする

**Comment by Huehara** [comment]
type:battleの最中に
「移動キー+ダッシュキー」
を押すと、スタミナを消費して回避動作をする



戦闘中は走れないようにする

**Comment by Huehara** [comment]
type:battleの最中に
「移動キー+ダッシュキー」
を一瞬押すと、スタミナを消費して回避動作をする

長押しで
走る
