### ISSUE TITLE
懐中電灯の光を実装

### ISSUE THREAD

**Issue by inosy22** [TeamLS/6chefs2#118]
夜廻り的な感じ
![151029_06](https://cloud.githubusercontent.com/assets/10849664/17742216/0c92ee32-64da-11e6-801d-88a66c50394b.jpg)

90度の視界の光画像を準備する
自分の周りには丸い光

方向転換したらアニメーションで光も動くようにする

**Comment by Huehara** [comment]
これ、大宝いる塔で使いたいから入れよう

アップデート版に入れるでいいから
いのすはこれ進めてて

**Comment by inosy22** [comment]
#252 と同時に実装済
