### ISSUE TITLE
カウントダウンの数字を可視化できるように

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#126]
可視化できるときとできないときがある

**Comment by inosy22** [comment]
これはどういうデザインで実現したい感じ？

**Comment by Huehara** [comment]
![image](https://cloud.githubusercontent.com/assets/11405126/18228800/fd4c5234-7298-11e6-8cc6-b3ff5231dfdb.png)
![default](https://cloud.githubusercontent.com/assets/11405126/18228802/0bc75976-7299-11e6-9eba-d3a8eef0a409.PNG)



こんなん
右上に
できれば小数第二位秒まで

**Comment by inosy22** [comment]
分はいらないっていう認識でOK?
例えば表記はあと9.5秒の時は「09.50」とか？

**Comment by Huehara** [comment]
そう

**Comment by inosy22** [comment]
理解、やっとく！

**Comment by Huehara** [comment]
オプションかなんかで
表示のオンオフできるようにしといて
ってのと

文字の色は
スタミナゲージと同じ色で

**Comment by inosy22** [comment]
おけー

**Comment by Huehara** [comment]
4c4f44d
セーブデータ10

stopCountしたら
数字の表示は消えるけど
数字のマクラはそのまま残って半透明の四角が残る


のとタイムアップしたときに
-0.02になるのは仕様？

あと
メニュー画面開きまくると時間が増える

**Comment by Huehara** [comment]
個人に動画貼ったので参照して

**Comment by inosy22** [comment]
ストップカウントの方いじるの忘れてた

**Comment by inosy22** [comment]
- 消えないのはstopCountしてないだけだと思う
 - タイムがマイナスになったら0になるようには修正した
 - メニュー画面開きまくると時間が増えるってのは、カウンターの数字がメモリから解放されて謎のアドレスが数字として表示されてるためなので、修正済み

**Comment by Huehara** [comment]
ちょっとまだ検証はできてないけど

カウントダウンの数字表示させてない時でも

マクラだけ出てたりしない？

**Comment by inosy22** [comment]
おっとまじか、確認してみる

**Comment by inosy22** [comment]
コード見た感じそんな感じはなさそうだけどな...

**Comment by Huehara** [comment]
そうか

なんかdisplay:trueにしてない時に
出てた気がしただけ

もっかい見てみる

無かったら閉じます
