### ISSUE TITLE
setCameraイベント

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#128]
objIDを指定して、そいつにカメラをついてこさせる。
何も指定がなかったら
主人公にカメラをもどす

**Comment by KoheiAsami2** [comment]
https://github.com/TeamLS/6chefs2/wiki/EventScript-API-Reference#setCamera

**Comment by Huehara** [comment]
"type":"if",
"condition":[
 ・・・
],
"action":[
　{
　　"type":"already"
　}
]
みたいにif分のactionの中にalreadyを入れるとalreadyが機能しない
もしくは
if文の条件クリアしてたらalreafy関係なく発動しちゃう
みたいな
if文の方の問題かも

if文消したら
2回目は見られなかったから

**Comment by Huehara** [comment]
type:camera後にsetCameraを書いても主人公にカメラ戻らず
サンプルはc4f9808
セーブデータ3
