### ISSUE TITLE
"type":"already"がちゃんと機能しない件について

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#141]
alreadyしたイベントがまた発動する
if分は正常に動くので見たことにはなってるっぽい
never againの機能が動いてないっぽい

2016/11/27 11:00　11:02頃にコミットしたセーブデータ9がサンプル
ただ、
mapID:8のeventID:13は
もう一回見ることはできなかった

**Comment by Huehara** [comment]
"type":"if",
"condition":[
・・・
],
"action":[
　{
　　"type":"already"
　}
]
みたいにif分のactionの中にalreadyを入れるとalreadyが機能しない
もしくは
if文の条件クリアしてたらalreafy関係なく発動しちゃう
みたいな
if文の方の問題かも

if文消したら
2回目は見られなかったから

**Comment by inosy22** [comment]
mapID: 13
eventID: 11
のイベントのalready実行時にログ出してみたけど、eventIDがちゃんと取れてないみたい
<img width="912" alt="2016-11-28 5 41 18" src="https://cloud.githubusercontent.com/assets/10849664/20651707/566ca54a-b52d-11e6-8df9-a86b5090ddc7.png">

**Comment by KoheiAsami2** [comment]
インスタンス変数の_callerには値入ってた？

**Comment by inosy22** [comment]
入ってなかったから直した

**Comment by inosy22** [comment]
ちょっと今細かい調整中

**Comment by KoheiAsami2** [comment]
あれ、マジで
どこから経由だと漏れてたんだろ

**Comment by inosy22** [comment]
spawnでcreateGameEventするときに漏れてたからとりあえずそこ追加したらなおった！
けど、そもそもルートになるイベントを生成する瞬間にEventIDがわからないという問題があってそこでどういう仕組みにしようか悩んでる

**Comment by KoheiAsami2** [comment]
spawnだったのか...
create関数の引数増やすとか...？
手間やばいけど、やろうかな

**Comment by inosy22** [comment]
createGameEventの中でGameEventインスタンスにmapIDとEventIDセットしたいな、そうでないとログが出しづらい
mapIdはcommonEventの事を考えると、classIdって名前でstringでもたせたいから以下のようにオーバーロード関数を作る
 - ルートイベントはclassIDとeventIDをセット
 - 子イベントはcallerセット必須
 - 子イベントとして、CommonEventもしくは同じマップの別イベントIDを呼ぶとき

できるようにすべきかな
```cpp
// ルートイベント生成
GameEvent* EventFactory::createGameEvent(rapidjson::Value& json, const string& classId, const string& eventId)
{
    GameEvent* event {nullptr};
    // event生成中略
    event->setClassId(classId); // こんなのないけどあるとしたら
    event->setEventId(eventId);
    return event; 
}

// 子イベント生成
GameEvent* EventFactory::createGameEvent(rapidjson::Value& json, GameEvent* caller)
{
    GameEvent* event {nullptr};
    if (!caller) return event;
    // event生成中略
    event->setCaller(caller);
    return event; 
}

// 子イベント生成 (ClassとEventID指定の場合
GameEvent* EventFactory::createGameEvent(rapidjson::Value& json, GameEvent* caller, const string* classId, const string& eventId)
{
    GameEvent* event {nullptr};
    if (!caller) return event;
    // event生成中略
    event->setCaller(caller);
    event->setClassId(classId);
    event->setEventId(eventId);
    return event; 
}
```

ちなみにバリデーションのログでEventIDがおかしい以外は、問題なく動作する状況まできてるので、それでとりあえずプルリク出します！

**Comment by inosy22** [comment]
という案

**Comment by KoheiAsami2** [comment]
いのすの案いいと思うんだけど、
callEventの扱いが難しいのよね...

**Comment by inosy22** [comment]
callEventは3つ目のメソッドでどうにかならない？
caller入れつつ、自分のEventIDをセットする形で、親のIDも子のIDも取れて、commonEventかどうかも判別できるし

**Comment by inosy22** [comment]
てか、3つ目のメソッドの説明が遠回しにcallEventのことになってる！

**Comment by Huehara** [comment]
とりあえずあの進めなかった場所はalreadyされてた
