### ISSUE TITLE
charaWalkとcharaWalkToがキャラを貫通して進む件について

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#148]
charaWalkToがキャラobjectのあたり判定を無視して進むので
止まっているキャラだけ
あたり判定扱いにして

歩き中のキャラのあたり判定は引き続き無視のままでいい

**Comment by Huehara** [comment]
キャラのあたり判定を無視しないで進むと
キャラを2人以上charaWalkToさせた時に
キャラがぶつかって歩くのをやめるから
charaWalkToではキャラのあたり判定は計算しない←今ここまで仕様

そうするとキャラを貫通して進むので
歩いてる途中のキャラのあたり判定のみを無視するように
改修

enhanceに変更

**Comment by KoheiAsami2** [comment]
追記ありがとう

**Comment by inazou** [comment]
直ってるんでdebugにします
