### ISSUE TITLE
繰り返し処理スクリプト

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#15]
type:repeat
times:int
action:[]

**Comment by KoheiAsami2** [comment]
発動したらEventTaskにasyncEventsとか名前つけたベクタにインスタンスを保持しておこう

たしかタイマー系イベントもどこかにとってあるんだけど、EventTadkの方に移動させたいな

GameEvent基底にフラグを入れるか、
runの一番最後に自分自身をEventTaskに保持させておく処理を入れなきゃいけない

**Comment by KoheiAsami2** [comment]
あ、timesが-1の時は無限ループになるようにしといて

**Comment by KoheiAsami2** [comment]
いや、ちょいまち。
これ普通に指定回数ループでいいや。
非同期イベントは別に作るわ

**Comment by inazou** [comment]
EventSequenceを継承して作ってもいいですか？

**Comment by KoheiAsami2** [comment]
いいよー

**Comment by KoheiAsami2** [comment]
#51

**Comment by Huehara** [comment]
これって結局times:-1で
無限ループになるようになってる？

**Comment by inazou** [comment]
なってます

**Comment by Huehara** [comment]
うい

**Comment by Huehara** [comment]
これって無限ループにしたときに

stopRepeatでループやめるようになってる？

**Comment by inazou** [comment]
stopRepeatはありません
