### ISSUE TITLE
デフォルトの画面サイズを 1.5倍 の方に変更してください

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#150]
デフォルトの画面サイズを
1.5倍
の方に変更してください

**Comment by inazou** [comment]
割り算の関係で、1.5を基準の1にすると1.0が2/3になって少数で表現できなくてツラいんですけど、サイズ直書きで
600*450

800*600

1000*750

1200*900 ←これデフォルトでいいですか？

**Comment by KoheiAsami2** [comment]
あ、なるほど...
それでいいと思う

**Comment by Huehara** [comment]
計算？
方法は同じで
何も設定してなかったら
1000＊750

ってできない？

デカイとディスプレイからはみ出る奴が
出てくる可能性がある

**Comment by inazou** [comment]
1.5倍1200*900なんですけど、デフォルトは1000*750の1.25倍のやつですか?

初期のサイズいじったら色々表示するものがおかしくなったんで、読み込み時に1.5倍するようにしたんで、計算はいらなくなりました

**Comment by Huehara** [comment]
今って最大が1.5？

ごめん勘違いしてた
1.25倍にして下さいー

**Comment by KoheiAsami2** [comment]
1.25倍になってるのを確認
