### ISSUE TITLE
かいりきでものを動かすと落ちる

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#155]
51a7f8c

でコミットしたセーブデータ6で下のマップに行くとやれる

索敵タイプの敵の進行コースを横断させて動かそうとすると落ちるのかもしれない

**Comment by Huehara** [comment]
敵の進行コースじゃないところに動かしても落ちた
2回押すと落ちる？

**Comment by inazou** [comment]
おそらく敵の存在は全く関係なくて、とにかく押したら落ちますね
