### ISSUE TITLE
マップチップの描画がされてないマップがある

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#158]
fd368fd
コミットしたセーブデータ8

y座標52より下のチップが描画されてない
レイヤー名：Base

何故

**Comment by Huehara** [comment]
![default](https://cloud.githubusercontent.com/assets/11405126/21079128/1662c756-bfcb-11e6-8635-1db379b82fb3.PNG)

**Comment by inazou** [comment]
<img width="994" alt="2016-12-12 00 56 58" src="https://cloud.githubusercontent.com/assets/12715455/21081268/242ec534-c006-11e6-9b45-d4b113087066.png">
<img width="1293" alt="2016-12-12 00 57 16" src="https://cloud.githubusercontent.com/assets/12715455/21081267/242d0d02-c006-11e6-936f-ae0d7e0d5adf.png">

**Comment by inazou** [comment]
Baseってやつ消して、適当にコピーしたレイヤー作ったら表示されたんで、プログラムが原因ではなさそうです

**Comment by inazou** [comment]
TiledでBaseを作り直してもらえると表示されると思われます

**Comment by Huehara** [comment]
ありがとう

**Comment by Huehara** [comment]
とり
