### ISSUE TITLE
鬼が消えてくれない件について

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#159]
ea5df2e
のセーブデータ6でスラックに貼った動画のところ行けます

mapID:"50"
eventID:"1"
でobjID："1452"を
出したんだけど

eventID:"8"(会話のやつ)で
{
	"type":"removeObject",
	"objID":"1452"
},
書いてるんだけど
鬼が消えてる気配がない
バーが出てるから

何故

**Comment by inosy22** [comment]
removeEnemyで鬼は消えるんだけど、
DetectionBoxが消えてない！

**Comment by inosy22** [comment]
#162
