### ISSUE TITLE
会話イベント終了後　鬼がいると落ちる件

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#160]
ea5df2e
のセーブデータ6でスラックに貼った動画のところ行けます

mapID:"9"
eventID:"9"

の会話イベントの後、落ちる

ちなみに会話イベント中
ID:1433,1434
の鬼がいるんだけど

この鬼を消したら
落ちませんでした。

鬼のmovePatternとかがミスってる？

調査お願い

**Comment by inosy22** [comment]
治りましたー
