### ISSUE TITLE
戦闘用パラメータ追加

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#164]
- 回避行動時のスタミナ消費値
- 攻撃モーション時のスタミナ消費値
- 回避モーション後硬直時間(秒)

**Comment by inosy22** [comment]
[基準値]
回避時のスタミナ消費: 25
攻撃モーションスタミナ: 5
回避モーション硬直時間: 0.0

**Comment by KoheiAsami2** [comment]
ついかで、攻撃モーションの硬直時間も欲しいかも
