### ISSUE TITLE
createLayerとremoveLayerが機能しない

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#168]
745f483

のセーブデータ7

"mapID":"63"
"eventID":"4"

{
	"type":"createLayer",
	"layer":"railChange1_2"
}
と
{
	"type":"removeLayer",
	"layer":"railChange1_2"
}
交互にやってるけど
レイヤーが出たり消えたりしない

その他のマップのremoveLayerとcreateLayerは動く

なぜ？

**Comment by inazou** [comment]
該当のセーブデータが見つからないです...

**Comment by Huehara** [comment]
ごめんみすった

aceaac2
の6で

**Comment by inazou** [comment]
ifの条件がおかしいかもしれないです

ログ見たらcreateLayerとremoveLayerが同時に動いてます

**Comment by Huehara** [comment]
なるほど
分かった

ありがとう
