### ISSUE TITLE
changeMapで落ちる件について

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#174]
9a68e86

セーブデータ3で
目の前の机に話しかけると始まるイベント
("mapID","eventID")の
("104","2")のイベント
changeMapで落ちる

なぜ
mapID書き換えてほかのマップには移動できた

調査頼む

**Comment by inosy22** [comment]
移動先のイベントスクリプトに問題があるんじゃないの？

**Comment by Huehara** [comment]
スクリプト切っても落ちたから
その可能性も含んでの質問

**Comment by inosy22** [comment]
このマップがなんかおかしいっぽい
TAIHOHEN-ORPHANAGE-corridor.tmx

**Comment by Huehara** [comment]
そう思って一回作り直したんだが

どう作り直せばいい？
何がいけない

**Comment by Huehara** [comment]
何がいけないんだーーーーー

**Comment by Huehara** [comment]
また作り直します

**Comment by inosy22** [comment]
tmxファイルの読み込みで落ちてるからよくわからん...

**Comment by inosy22** [comment]
Layerの情報取ろうとして落ちてるところまではわかった

**Comment by Huehara** [comment]
map作り直したらマップ移動はできたけど

その先のスクリプトで落ちた
こちらはもう少しこっちで見てみる

**Comment by Huehara** [comment]
changeMapの中で
移動先マップのイベント呼んでるんだけど("105","2")

そのイベントの冒頭の
"type":"fadein"
消したら動いた

fadein

こちら一応落ちない方法は見つけたから
調査に時間かかりそうなら後回しでも大丈夫

**Comment by inosy22** [comment]
落ちない方法って？

**Comment by Huehara** [comment]
ここで
fadeout
fadein使わない

**Comment by inosy22** [comment]
普段は動くのに、このイベントだけ動かないってことは、何か他のマップと違って特殊なことしてるとかないかな？

**Comment by Huehara** [comment]
分からんもうちょい見てみる

**Comment by KoheiAsami2** [comment]
fadein fadeout程度ならすぐ調査できそう

**Comment by Huehara** [comment]
手すきでいいから頼む

**Comment by Huehara** [comment]
このchangemapで落ちる件
他にも何箇所か起きて

どこも
同じマップ作り直したら落ちなかったから

マップファイルが"壊れてる"ってやつかも知れん

マップファィルが壊れるってなんじゃい
って感じだけど

**Comment by KoheiAsami2** [comment]
まあフリーソフトだしありえんじゃ

**Comment by KoheiAsami2** [comment]
ありえるんじゃ

**Comment by Huehara** [comment]
１つずつレイヤー消して試したけど落ちたから
特定のレイヤーが悪さしてる
ってわけでもなさそう

**Comment by Huehara** [comment]
16a16b2
のセーブデータ5

今度は2回くらいマップ作り直したけど無駄だった
これホントになおせないやつ？
