### ISSUE TITLE
charaMoveToで目的地までたどり着かない

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#175]
9a68e86

セーブデータ3で
目の前の机に話しかけると始まるイベント
("mapID","eventID")の
("104","2")のイベント
大宝少年のcharaWalkToで
出口にたどり着かないまま
次のremoveObjectが発動している。

こっちもあわせて調査お願い

**Comment by inosy22** [comment]
@naniwo こっちは普通にプログラムのバグの可能性

**Comment by inosy22** [comment]
こうしたらうまくいったので、探索アルゴリズムが間違ってるね
```
{
    "type":"charaWalkTo",
    "objID":"10222",
    "x":14,
    "y":27
},
 {
    "type":"charaWalkTo",
    "objID":"10222",
    "x":14,
    "y":27
},
{
    "type":"removeObject",
    "objID":"10222"
},
```

**Comment by Huehara** [comment]
2連でうまくいくなら
とりあえずコミケ版はこのままいく？

**Comment by inosy22** [comment]
そうだね、取りあえず2連にしとけば、直ったとしても影響ないはずだからそれで！
パーフェクトチェイサーのバグのせいだから、ナニヲ戦闘終わったら直してくれー

**Comment by inazou** [comment]
#148と#153と共通な気がするんで、コミケまでに直さないといけないかもです

**Comment by inosy22** [comment]
あー同じっぽい

**Comment by inazou** [comment]
a-starの実装にバグがあるんですよね。
当たり判定が取れなくて、全てを無視した最短距離が返ってきちゃうところまではわかってるんですけど、なにしたらいいのかはわかんないです

**Comment by inosy22** [comment]
俺も昨日A-star調べたんだけど、前からこんなバグ持ってたっけ？
コマンド型にしてから、Directionの生成方法が間違ってる気がしてたりする

下の4マスの右上に主人公がいて、左上が当たり判定、目標が左下だとすると、Directionの生成が左→下になってたりしないかな？
●○
○○

昨日ちょろっと見たら、斜めに移動したいときのディレクション生成が左右を決めてから上下を決める形で、当たり判定オブジェクトの有無が加味されていなかったような....ちゃんと読んでないからわからないけど

**Comment by Huehara** [comment]
普通のオブジェクトのあたり判定も無視してるのか…

**Comment by KoheiAsami2** [comment]
キャラクタとして生成したオブジェクトはa-starから当たり判定が無視される仕様なんで、そこはバグではない

**Comment by KoheiAsami2** [comment]
ただ、それ実装した後上原に、移動中のオブジェクトだけ当たり判定を無視するように注文きたからそれを直す必要はあり

**Comment by KoheiAsami2** [comment]
それと、目的地までたどり着かないバグは別物と考えて

**Comment by KoheiAsami2** [comment]
上原もバグチケ作るだけじゃなくて、どういう経緯でこうなったか説明した方がいいよ

**Comment by KoheiAsami2** [comment]
A-starの変更点は、
前は全てのオブジェクトから当たり判定のRectを取り出して判定してたのを、CollisionDetectorに委譲した
そこにバグの可能性もあり

**Comment by Huehara** [comment]
どういう経緯っていうと最初のコメじゃダメなん？


キャラのあたり判定無視してるのとは別だし

**Comment by inosy22** [comment]
本来は上原にもうちょっと調査した上でチケット発行して欲しいけど、今は急いでるから俺と稲見に調査任せた方が早いしそれでいいいよ！

**Comment by Huehara** [comment]
いや
他に載せる情報あったら教えて

**Comment by KoheiAsami2** [comment]
稲見がキャラの当たり判定無視すんのバグだと思ってるでしょ
別にこのissueに限った話じゃない

**Comment by KoheiAsami2** [comment]
それによって、実際に問題が発生してる場所に辿り着く時間が変わってくるんで、キャラの当たり判定の経緯は説明したのかなと

**Comment by KoheiAsami2** [comment]
因みに探索が間違ってたら
戦闘のAI完成しないから先こっちだな

**Comment by Huehara** [comment]
そっちかごめん
それこの前言われたやつだな
漏れてた
すぐチケット修正します
以後書くようにします

**Comment by KoheiAsami2** [comment]
チケットに書くかどうかじゃなくて、伝わればもうなんでもいい

**Comment by Huehara** [comment]
ナニヲだっあら口頭で
