### ISSUE TITLE
type:repeatで落ちる

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#180]
dd9bdb7
でコミットしたセーブデータ9

子供に話しかけた時に発動するはないちもんめイベ
その中でcallEventしてる
("81","9")

```
{
			"type":"repeat",
			"times":-1,
			"id":"1",
			"action":[
				{
					"type":"sequence",
					"action":[
						{
							"type":"spawn",
							"action":[
							]
						},
						{
							"type":"spawn",
							"action":[
							]
						}
					]
				}
			]
		}
```
1順目は落ちなかったけど
2順目以降
繰り返しに入ったら落ちる。

type:repeat
消したら落ちなかった。

これ
ちょっとスクリプト長いのもあるから
調査頼む

**Comment by inazou** [comment]
色んな所で_jsonに代入しちゃってるんで、repeatで保持してるjsonが２回目以降のときに使えなくなっちゃってるのが原因だと思うんですけど、rapidjson::Value& jsonのコピーとかってできます？

**Comment by KoheiAsami2** [comment]
大元のやつからコピーするのは、EventScriptクラスに実装してある
でも、この場合、GameEventのインスタンスを使いまわすとかできないかな

**Comment by inazou** [comment]
そもそもGameEventでコピーを作って持たせるようにしました

**Comment by inazou** [comment]
#184 はブランチミスったんで気にしないでください
