### ISSUE TITLE
charaWalkToしはじめなくて進めない

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#208]
218e915
でコミットしたセーブデータ7

右へ右へ逃げていくと発動する
ヨシツネが撃たれるイベント

イベント中に大宝がcharaWalkToするはずなんだけど
動かなくて先に進まない

前まで動いてた

なぜ

**Comment by inosy22** [comment]
今試したけど、このマスたどり着けないからじゃない？
yを12にしたらいけたよ
```json
{
    "type":"charaWalkTo",
    "objID":"hero",
    "x":67,
    "y":12,
    "speed":2.0
}
```

**Comment by inosy22** [comment]
charaWalkToよくわからないけど、たどり着けないと動くの止めるっぽいから
座標調整してどこから動けなくなるのか確かめて

**Comment by Huehara** [comment]
仕様勘違いしてた
座標ずらしたら
動いた
