### ISSUE TITLE
キャラメッセージでもクエスチョンメッセージにできるように

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#22]
{
    "type”:”questionMsg",
    “frame”:”chara”,→今までのやつの場合は”system”
    "text":["うしろのしょうめんだーあーれぇ？"],
    "charaID":"10",
    "name":"しろう"
    "choices":[
        {
            "choice":"かずお",
            "action":[

```
        ]
    },
    {
        "choice":"にこ",
        "action":[

        ]
    }                                           
]
```

}

**Comment by inazou** [comment]
やりまーす

**Comment by KoheiAsami2** [comment]
ありがとー
DispImageLayerを再利用する形がいいと思う

**Comment by KoheiAsami2** [comment]
ありがとー

**Comment by Huehara** [comment]
・frame廃止で
　今までのquestionMsgはデフォルトで
　charaIDがあったら、デザインをキャラメッセージにして
　nameの仕様はキャラメッセージと同じで

**Comment by inazou** [comment]
これってキャラと会話している途中でquestionMsgは出来ない仕様でいいんですか？

**Comment by KoheiAsami2** [comment]
できなくて大丈夫。別々に扱ってもらう

**Comment by inazou** [comment]
imgIDはいらない感じですか?

**Comment by KoheiAsami2** [comment]
うーん表情差分は組み込みたいはずだから必要

**Comment by KoheiAsami2** [comment]
#57
