### ISSUE TITLE
戦闘用敵が少ししたらサボる

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#222]
しばらく戦闘してると
敵が動くのをやめる

間合いに入ったら攻撃はしてくるけど

調査
は明日永田町でもいいや

**Comment by KoheiAsami2** [comment]
#226

**Comment by Huehara** [comment]
[サボり.zip](https://github.com/TeamLS/6chefs2/files/751988/default.zip)

**Comment by Huehara** [comment]
↑参考動画

1e48bd9
のセーブデータ8

敵の攻撃モーション中に別のイベント起きると
敵の動き止まるっぽい

**Comment by KoheiAsami2** [comment]
イベント発生時に攻撃モーションも一時停止させるようにする（させるべきだった）

**Comment by KoheiAsami2** [comment]
直った
