### ISSUE TITLE
画像出しながらキャラメッセージ送り

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#23]
（例）
{
            "type":"charaMsg",
            “img”:”airplane.png",
            "talk":[

```
]
```

}

**Comment by Huehara** [comment]
fileで指定した画像を表示しながら
キャラメッセージ表示

**Comment by Huehara** [comment]
![default](https://cloud.githubusercontent.com/assets/11405126/21079487/377667f8-bfd6-11e6-94c6-5d29491a9df0.png)

**Comment by Huehara** [comment]
会話中はこんなんで

**Comment by Huehara** [comment]
![manaka_juiced](https://cloud.githubusercontent.com/assets/11405126/21079493/4f044cbe-bfd6-11e6-86f0-a5027686ba81.png)

**Comment by Huehara** [comment]
会話を全部読み終わったら
画像のみが残って

ここで決定を押すと
画像も消える

**Comment by Huehara** [comment]
![default](https://cloud.githubusercontent.com/assets/11405126/21229229/3202bc9e-c324-11e6-9c8a-0ebba6a04066.PNG)

**Comment by Huehara** [comment]
5cc9961
セーブデータ9

この娘に話しかけて発動するイベント
("109","4")
の中で
{
 "type":"charaMsg",
"img":"haori.png",
"talk":[
  {			
	"text":["ほら。"],
	"charaID":"31",
	"imgID":"3",
	"miniChara":true
 }
]
},

で落ちる


"img":"haori.png"
の部分を無くすと動く

また、
displayImgでhaori.pngの表示自体はできた。

使い方間違ってる？

**Comment by inazou** [comment]
あーdisp/haori.pngに変えてもらえれば動くんですけど、標準でdisp/の中を見る設定の方がいいですか？

**Comment by inosy22** [comment]
生pngを見る場合はdispの中の画像参照する仕様なはずだから、dispの中見るようにしよう！

**Comment by inazou** [comment]
失礼いたしました

**Comment by Huehara** [comment]
あーなるほどそういうことか

すまん
デフォでdispから見るようにおねがい

**Comment by Huehara** [comment]
このissueもうもらっていい？

**Comment by inazou** [comment]
お願いします

**Comment by inazou** [comment]
フェードイン、フェードアウトするようにしました
