### ISSUE TITLE
セーブメニューを出現させるイベントを実装

### ISSUE THREAD

**Issue by inosy22** [TeamLS/6chefs2#240]
セーブメニューを出現させるイベントを実装する。

## 概要
イベントタイプ名は"displaySaveMenu"
セーブする場所と続きからを押した時に発火するEventIDを指定できる。

## オプション詳細表
以下のオプションは全て必須ではないので、指定されていない場合はデフォルト値になる。

| オプション名 | 型 | デフォルト値 |
|:-----------|:------------|:------------|
| mapID | string | 現在の主人公のマップ |
| x | int | 現在の主人公のx座標 |
| y | int | 現在の主人公のy座標 |
| direction | string | 現在の主人公の向き |
| eventID | string | なし |

## 使用例
その場でセーブさせたいだけの時
```json
{
  "type": "displaySaveMenu"
}
```

続きからの時にイベント発火させるけど、場所はそのままの時
```json
{
  "type": "displaySaveMenu",
  "eventID": "1"
}
```

続きからの時の場所を指定して、イベントも発火させたい時
```json
{
  "type": "displaySaveMenu",
  "mapID": "1",
  "x": 1,
  "y": 1,
  "direction": "UP",
  "eventID": "1"
}
```

**Comment by Huehara** [comment]
これって鬼いるときにセーブウインドウ呼び出すと落ちる？

**Comment by Huehara** [comment]
普通の時に出そうとしても落ちる

4a334df

セーブデータ3の
機会に話しかけた時をdispkaySaveMenuにした
けど落ちた

**Comment by inosy22** [comment]
鬼いるときでも理論上大丈夫だけど、鬼いる状態で試してなかった！

**Comment by inosy22** [comment]
eventID指定しないと落ちるようになっちゃってたから直した！
