### ISSUE TITLE
動画再生

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#242]
mp4なりaviなり動画を再生。

ザラスのサークルロゴが出た後PV流す。

あと
movieってリソースフォルダ作って
その中に動画入れて
"type":"playMovie",
"file":"～.mp4"

みたいに動画再生するスクリプトも

"opption":"skip"
みたいなの書いたら
決定キー入力で動画再生中止してスキップできるようにする機能も欲しい

**Comment by inosy22** [comment]
option:skip じゃなくて
skip: true の方がいいかな

**Comment by Huehara** [comment]
そこはなんでもいいわ

**Comment by KoheiAsami2** [comment]
feature/play_video
に申し訳程度の途中分

http://dranger.com/ffmpeg/tutorial03.html
これドキュメントとして読んで

https://github.com/luochong/Cocos2dxVideo
ここでffmpegでデコードした映像のキャプチャをcocosに渡す方法見れる

**Comment by inazou** [comment]
VideoLayerってクラス名にしちゃったので
videoってリソースフォルダ作って
その中に動画入れて
"type":"playVideo",
"file":"～.mp4"

って感じでもいいですか?

**Comment by Huehara** [comment]
り

**Comment by inazou** [comment]
使い方
```
"type":"playVideo",
"file":"OPmovie.mp4",
"skip":true
```

**Comment by Huehara** [comment]
playVideoが動かないというか1フレーム目で止まる、
（OPは動く）

エンディングの時に困るから
大物そうなら前の
動画じゃなくてマップとして直接描画
という抜け道もあるにはある

けどやってみて
