### ISSUE TITLE
水没シーンの修正

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#245]
![default](https://cloud.githubusercontent.com/assets/11405126/22613265/5622edde-eaba-11e6-88b7-2a8af664044d.png)

画面の端で切れてると紙みたいに見えるから
横と下は十分な大きさにして
端が見えないようにしてほしい

か

十分な大きさの長方形を置いて
その上から今の小さい波を置いて欲しい

とりあえず
画面の端に黒いところが見えないようにしてほしい

**Comment by inosy22** [comment]
下なくすのむずかったから、とりあえず横の波打ちなくした状態で確認してくれー
これでもまだ、下無くしたかったら言って
