### ISSUE TITLE
メニュー画面のパーティ表示の人数制限設定

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#246]
![default](https://cloud.githubusercontent.com/assets/11405126/22615276/b7255094-ead4-11e6-80c4-057103e223fc.PNG)

メニュー画面のパーティは最大4人まで

主人公+パーティに加わった順

spanで加わったりして判断つかない場合は

主人公+キャラID若い順3人

で頼む

**Comment by Huehara** [comment]
アイテム装備したときレイアウト崩れるのは
今回は保留で

**Comment by inosy22** [comment]
spawnのときの順番はIDソードじゃなくてプログラムの追加順に任せるじゃダメ？

**Comment by inosy22** [comment]
そうしないと、パーティーの並び順とメニューの表示順が変わっちゃうから、なかなか面倒になってしまう
メニューでの並び順じゃなくて、そもそものパーティーの並び順をソートしなきゃいけないって話になる

**Comment by Huehara** [comment]
並び順はなんでもいい

最大4人になればなんでもいいわ

**Comment by inosy22** [comment]
おけー
