### ISSUE TITLE
懐中電灯、マップオブジェクトに

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#252]
{
			"type":"setTorch",
			"objID":"1517",
			"direction":"DOWN"
		}

こんなん

**Comment by Huehara** [comment]
{
"type":"setFlashlight",
"objID":"1517",
"direction":"DOWN"
}

こうね？

**Comment by Huehara** [comment]
これ、removeFlashlight
もお願い

**Comment by inosy22** [comment]
もちろん作るので問題なし！

**Comment by inosy22** [comment]
ちぇっくよろです
https://github.com/TeamLS/6chefs2/pull/260
