### ISSUE TITLE
イベントコール追加

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#28]
type:”callEvent”
“eventID”:int

**Comment by RyoyaIno** [comment]
eventIDはstringにします

**Comment by KoheiAsami2** [comment]
GameEvent::runの時に表に出てるマップのイベントを呼べるようにしないとね...

**Comment by RyoyaIno** [comment]
それするとしたら、全部変えなきゃならなくない？
GameEvent::initの時とGameEvent::runのときにマップが違うのってもともと全体的に対応してなくない？

**Comment by KoheiAsami2** [comment]
その通りなんだけど、こいつ以外の仕様を変えるのは手間かかるから、deplicatedって事にしといて、とりあえずこいつだけその仕様にしておきたい
基本ミニゲーム系のイベントにはコールバックイベント付いてるから、そこに新仕様のこいつを使っていきたい

**Comment by RyoyaIno** [comment]
マップをまたぐ仕様に対応するってことだったら、CommonEventScriptで対応したほうがいい気がする。

そうしないと、違うイベントスクリプトのeventID書かなきゃならなくなるし、マップ移動を許容する前提だと、実行時にどのマップにいるかわからないから、GameEvent::updateとかGameEvent::runの動作が安定しなくなりそう...。

現状、`className`でCommonEventScriptのクラス名指定できるから、マップまたいでも実行したいイベントはそこに書けばいいんじゃないかな？

**Comment by KoheiAsami2** [comment]
CommonEventScriptの中身がカオスになりそうだけど、それでいいか
