### ISSUE TITLE
キーコンフィグ機能

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#38]

**Comment by KoheiAsami2** [comment]
#46

**Comment by KoheiAsami2** [comment]
見た目とロジックは作ったから、データだけやっといて
適用ってとこで決定キー押した時だけ保存するように

**Comment by Huehara** [comment]
キーコンフィグの反映はリアルタイムに
保存は閉じた時でいい

**Comment by Huehara** [comment]
決定キーはz,enter,spaceどれでも反応するように
で決定キーはキーコンフィグ画面から消す。

キーコンフィグの反映は適用押してから
