### ISSUE TITLE
新しい地形「梯子」

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#5]
通る時に必ずUPに向かせる

**Comment by Huehara** [comment]
terrainの名前は

ladder


で

**Comment by inazou** [comment]
サンプルのマップとかってあります?

**Comment by Huehara** [comment]
56番
で

**Comment by inazou** [comment]
これ上向かせるのはできたんですけど、アニメーションはどうすればいいですか?

**Comment by KoheiAsami2** [comment]
UPのアニメーションだけながすようにするんじゃないの？
それともその方法を聞いてるの？

**Comment by Huehara** [comment]
流すアニメーションはUPのもので

**Comment by inazou** [comment]
歩行のUPのアニメーションだけ流すとスライドしてるみたいで気持ち悪いんですけど歩行のアニメーションをそのまま使っちゃっていいんですかってことで聞きました

**Comment by KoheiAsami2** [comment]
上方向に伸びるはしごにしか使わないっていう感じなのでは

**Comment by Huehara** [comment]
上下に伸びる梯子にしか使わない

し
スライド感はある程度仕方ないと思うから
とりあえずUPのアニメーションでオナシャス
