### ISSUE TITLE
かいりきイベ

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#59]

**Comment by Huehara** [comment]
物が乗ったとき、離れたときってトリガーの追加
動かせるオブジェクトの追加

**Comment by KoheiAsami2** [comment]
動かせる物(eventレイヤ上のもの)にはカスタムプロパティで
movable trueを指定する

**Comment by inazou** [comment]
動かせるオブジェクトって何で判断すればいいですか？

**Comment by KoheiAsami2** [comment]
setMovableっていうイベントを用意してフラグ管理しよう

**Comment by inazou** [comment]
<object id="78" x="320" y="208" width="32" height="16">
   <properties>
    <property name="EventID" value="6"/>
    <property name="trigger" value="2"/>
   </properties>
  </object>
これのプロパティに入れる感じじゃなくてイベントスクリプトで制御ってことであってます？

**Comment by KoheiAsami2** [comment]
それであってる

**Comment by inazou** [comment]
動かしたいものはオブジェクトid必須で

**Comment by inazou** [comment]
```
"type":"setMovable",
"objID":"102"
```
で指定されたobjIDの物体が動くようになります

**Comment by inazou** [comment]
```
"type":"deleteMovable",
"objID":"102"
```
で指定されたobjIDの物体が動かなくなります

**Comment by inazou** [comment]
```
"type":"setUnmovable",
"objID":"102"
```
で指定されたobjIDの物体が動かなくなります

**Comment by Huehara** [comment]
押したときにSE鳴らしたいんだけどできる？

一応全部同じSEでいいから

**Comment by Huehara** [comment]
っていうのと

動かせるものを
鬼にぶつけたとき、
鬼を貫通しないようにもできればしてほしい

できれば

**Comment by KoheiAsami2** [comment]
鬼にぶつけた時鬼を貫通しないようにした
あと、鬼が塊で動かない様にした

**Comment by KoheiAsami2** [comment]
鳴らすSEの指定ある？

**Comment by Huehara** [comment]
seフォルダの
kairiki_move.mp3

鳴らしたい

**Comment by inazou** [comment]
```
{
"type":"setMovable",
"objID":"203",
"movable":true,
"file":"kairiki_move.mp3"
}
```
こんな感じで好きな音鳴らせます

**Comment by inazou** [comment]
音を設定していなかった時と壁とかにぶつかって押せなかったときは音は鳴りません
