### ISSUE TITLE
敵をMapObjectとして扱えるように

### ISSUE THREAD

**Issue by KoheiAsami2** [TeamLS/6chefs2#93]
- objIDで指定
- objIDで削除

**Comment by Huehara** [comment]
---イベント発動
敵の動きロック
敵を動かす
敵の動きロック
---イベント終了
敵の動きアンロック

が理想の動き方だったけど
---イベント終了
の後に、主人公が動かないと鬼も動かないので
イベント終了後即追いかけてくるようにしてほしい。

↓セーブデータ

{"status":1,"token":"1455956/P1kAlMiG2Kb7FzP5tM1QBI6DSS92c31Apgjk9lVK7d","save_count":13,"play_time":2059,"chapter":1,"bgm":["dark_chapter1.mp3"],"equipment_right":0,"equipment_left":0,"map_id":21,"party":[{"chara_id":0,"obj_id":-2,"x":61,"y":14,"direction":3},{"chara_id":1,"obj_id":1035,"x":63,"y":14,"direction":3}],"friendship":{"1":-1,"2":-1,"3":-1,"4":-1,"5":-1},"event":{"1":{"2":-1,"1":-1,"9":-1,"11":-1,"13":-1,"7":-1,"5":-1,"14":-1},"2":{"4":-1,"14":-1},"8":{"6":-1},"9":{"5":-1},"10":{"6":-1},"7":{"5":-1},"6":{"6":-1},"11":{"5":-1,"9":-1},"12":{"5":-1,"11":-1,"12":-1,"13":-1},"13":{"6":-1},"14":{"3":-1},"16":{"6":-1,"2":-1,"7":-1},"17":{"2":-1},"5":{"5":-1},"18":{"4":1,"6":-1,"5":-1},"20":{"4":-1},"21":{"6":-1}},"items":{"0":{"equipment_left":0,"equipment_right":0,"item":["151","152","153"]},"7":{"equipment_left":0,"equipment_right":0,"item":[]}},"chara":{}}

**Comment by Huehara** [comment]
やっぱりまだ
イベント終了後即動きださない

今プッシュしたセーブデータ1で
右に歩いてけばサンプルイベント見れる

**Comment by Huehara** [comment]
のと

removeObjectでもremoveEnemyでも
objID指定して敵消せない

timesとかのは消えるけど

**Comment by KoheiAsami2** [comment]
サンプルは？

**Comment by Huehara** [comment]
今コミットしたやつのセーブデータ3

イベントの出し方はスラックに貼った
イベントは["50","8"]

**Comment by Huehara** [comment]
removeObjectで消えたパターンもあったからはっとく
今のコミットのセーブデータ6で
下の階段降りたとこ
ただ、こっちは見た目だけ消えてて
そのあと見えない何かに殺される

**Comment by Huehara** [comment]
これ閉じるよ
