### ISSUE TITLE
連打イベでたまに落ちる

### ISSUE THREAD

**Issue by Huehara** [TeamLS/6chefs2#97]
連打イベで落ちるのが何回か起きた。

ゆっくり連打したらダイジョブだった

確定ではなさそうなので
要調査

**Comment by RyoyaIno** [comment]
ん？連打ツール使っても大丈夫だったんじゃないの？

**Comment by Huehara** [comment]
連打数が問題じゃないのかも

**Comment by KoheiAsami2** [comment]
これ問題なさそうだからcloseします
